# Generated by Django 4.2.7 on 2024-01-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vaga", "0002_remove_vaga_status_vaga_disponivel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaga",
            name="numero",
            field=models.CharField(max_length=2, verbose_name="Número da vaga"),
        ),
    ]
