# Generated by Django 4.2.7 on 2024-01-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserva", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="status",
            field=models.CharField(
                choices=[
                    ("em_andamento", "Em andamento"),
                    ("finalizada", "Finalizada"),
                ],
                default="em_andamento",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
