# Generated by Django 4.2.7 on 2024-01-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserva", "0002_alter_reserva_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="num_vaga",
            field=models.IntegerField(default=0),
        ),
    ]
