# Generated by Django 4.2.7 on 2024-01-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserva", "0003_reserva_num_vaga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="num_vaga",
            field=models.IntegerField(),
        ),
    ]
