# Generated by Django 4.2.7 on 2024-01-09 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vaga", "0001_initial"),
        ("reserva", "0006_remove_reserva_num_vaga_reserva_vaga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="vaga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vaga.vaga"
            ),
        ),
    ]
