# Generated by Django 4.2.7 on 2024-01-10 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reserva", "0008_alter_reserva_tipo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reserva",
            name="tipo",
        ),
    ]
