# Generated by Django 4.2.7 on 2023-11-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=12, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data_Nascimento')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
            ],
        ),
    ]
